//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestinyPCLoadoutManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public long SelectedGuardian {
            get {
                return ((long)(this["SelectedGuardian"]));
            }
            set {
                this["SelectedGuardian"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsSerializeAs(System.Configuration.SettingsSerializeAs.Binary)]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::DestinyPCLoadoutManager.Auth.Models.TokenResponse AuthToken
        {
            get
            {
                return ((global::DestinyPCLoadoutManager.Auth.Models.TokenResponse)(this["AuthToken"]));
            }
            set
            {
                this["AuthToken"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsSerializeAs(System.Configuration.SettingsSerializeAs.Binary)]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<DestinyPCLoadoutManager.API.Models.Loadout> Loadouts {
            get {
                return ((global::System.Collections.Generic.List<DestinyPCLoadoutManager.API.Models.Loadout>)(this["Loadouts"]));
            }
            set {
                this["Loadouts"] = value;
            }
        }
    }
}
